-- Migration: Catalogue Updates

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS subcategory_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS gallery_images JSONB,
ADD COLUMN IF NOT EXISTS exotic BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS premium BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS short_description TEXT;
